create table public.message (
  id bigint generated by default as identity not null,
  name text not null,
  message text not null,
  image_url text not null,
  created_at timestamp with time zone not null default now(),
  constraint public.message_pkey primary key (id, name, message, image_url, created_at)
) TABLESPACE pg_default;

grant insert, select on public.messages to anon;
