create table public.messages (
    id bigint generated by default as identity primary key,
    name text not null,
    message text not null,
    image_url text not null,
    created_at timestamptz default now()
);

alter table public.messages enable row level security;

grant select, insert on public.messages to anon;

create policy "Anyone can read messages"
on public.messages
for select
to anon
using (true);

create policy "Anyone can send messages"
on public.messages
for insert
to anon
with check (
    char_length(name) between 1 and 100
    and char_length(message) between 1 and 5000
);

create policy "Anyone can upload drawings"
on storage.objects
for insert
to anon
with check (
    bucket_id = 'drawings'
);

create policy "Anyone can view drawings"
on storage.objects
for select
to anon
using (
    bucket_id = 'drawings'
);

alter publication supabase_realtime
add table public.messages;
